travis:
  secure:
    BINSTAR_TOKEN: ek70uIbl+LPt1K5uveJ3VG1BzZRps58z8EiXkBNjFnSjfSCz5zGGg3vbNOiXjHuPhVR7tKC+y6gV7r+WKJF3M5VOBEhLfCGLLAkqIZaDqVz2FM1qlR1sOiN+jr2GOy6rfGlyYJ180nT4WHViqVPR7evXUQZ7pqrdDIBv/Ra4sP9ZY/L42G+Nce1OgoeCnLjOU5wVxqJWVncjk75NT8JskoLxSmrwY2WtP/qucRdEpiVRDsvxZfBk5cLZCGN8pAqlRJgORpwLdCgEEGF9nmc+zUV8qQCqaTOx03+LMQQM4Jw3kolGbK1NFzIclVeCMBx6yT7nUdAbYny2u61XshehLdQv18cTf7RIPw9lw1NzISiBuuMGImB+ui74i0gmDG/EYwJEnIGKPhmbw+2WwV4RKz8nfzg136bsX1MeODn4E83K5wpVAUDf4U0gvG4tmGd9EYSMnlo0MWkGXI7r3hWKzmDCRtvgH9eR8jTj6YVz73wsTfjxPYYdtkMoEhi7V1K25oslCoAfQVpF7O2jTWhmj5L+PTqnoZTZqBnDl7iQ9QBny19VdfqXQYrxavX9yOpXUadFOR8xyN78y2n/QpiKbdE2E5QRfA/5ondDGsbD1KjggDANjRMqD7hY5eV++Qi9bO3WLPjxeGRgj0HxcqrzjCYY5yo+DPLqwfiqk0x9pqM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
